language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION_CEILING=1.4
  - DJANGO_VERSION_CEILING=1.5
  - DJANGO_VERSION_CEILING=1.6
  - DJANGO_VERSION_CEILING=1.7
  - DJANGO_VERSION_CEILING=1.8
install:
  - pip install -q "Django<$DJANGO_VERSION_CEILING"
  - pip install -q flake8 pylint pylint-django django-nose
  - pip install -e .
script:
  - python setup.py test
  - flake8 tests src setup.py
  - pylint --rcfile=pylint.rc src/django_richenum
  - pylint --rcfile=pylint.rc tests
  - pylint --rcfile=pylint.rc setup.py
