dist: xenial
language: python
sudo: false
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
services:
  - mysql
  - postgresql

install: pip install tox-travis
before_script:
  - "mysql -e 'create database testdb;'"
  - "psql -c 'create database testdb;' -U travis"
script: 
  - tox
  - tox -e lint